### ISSUE TITLE
GetLastNotificationIntent returns null when tapping on a group of notifications

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/com.unity.mobile.notifications#19] opened 2020-03-18 08:16 UTC
Tested on master and on 1.0.4-preview.9
Device is Google Pixel 2, Android 10

Repro video:
https://drive.google.com/file/d/1hTUmIgdNGmtiFMcjXDipq3-z0YZ7MLcK/view?usp=sharing

**Comment by vincent-unity** [comment] 2020-03-18 11:56
AndroidNotificationCenter.GetLastNotificationIntent() calls Activity.getIntent() to get the last intent set to the Activity. 
1. If you tap on a specific notification, the intent with valid notification data in `Extras` will be returned by `AndroidNotificationCenter.GetLastNotificationIntent()`. 
2. If you tap on the group, an intent generated by system will be set to Activity and returned by Activity.getIntent(). This intent doesn't contain any notification info in the extras, so we treat it as not a notification intent, `AndroidNotificationCenter.GetLastNotificationIntent()` will return null in this case.

**Comment by vincent-unity** [comment] 2020-06-03 01:52
Closed as by design.

**Closed by vincent-unity** 2020-06-03 01:52 UTC
