### ISSUE TITLE
crash on android 5.1 api version less than 23

### ISSUE THREAD

**Issue by pigerj** [Unity-Technologies/com.unity.mobile.notifications#188] opened 2022-05-11 16:16 UTC
you need to check if the current android version higher or equal to 6.0 - api 23 in order to use `getActiveNotifications` function.
it CRASH on android 5.1 on lower.
or you can set minimum api to 23.
![Capture](https://user-images.githubusercontent.com/70137755/167897791-bdc54431-4d4d-45ae-8c51-f4ae2c399cab.JPG)

**Comment by aurimasc** [comment] 2022-05-12 08:55
Duplicate of case 1423875 with PR in progress.

**Closed by aurimasc** 2022-05-12 08:55 UTC
