### ISSUE TITLE
iOS 15 app crashes on getPendingNotificationRequestsWithCompletionHandler

### ISSUE THREAD

**Issue by yanmasharski** [Unity-Technologies/com.unity.mobile.notifications#121] opened 2021-09-29 08:17 UTC
Hi, Unity Team!

We detected app crash because of calling **getPendingNotificationRequestsWithCompletionHandler** method.
We made fast fix because we can't stop development process, but this issues should be critical for all users.
Hope, you will fix this soon.

Our fix:

```
- (void)updateScheduledNotificationList
{
    UNUserNotificationCenter* center = [UNUserNotificationCenter currentNotificationCenter];
    static dispatch_once_t onceToken_2 = 2;
    dispatch_once(&onceToken_2, ^{
        [center getPendingNotificationRequestsWithCompletionHandler:^(NSArray<UNNotificationRequest *> * _Nonnull requests) {
            self.cachedPendingNotificationRequests = requests;
        }];
    }];
}
```

**Comment by mpeggdev** [comment] 2021-10-07 09:55
Thanks to the above comment we also managed to fix the issue. However, we chose to use dispatch_async rather than once so subsequent calls to the function will also work:
```
- (void)updateScheduledNotificationList
{
    UNUserNotificationCenter* center = [UNUserNotificationCenter currentNotificationCenter];
    dispatch_async(dispatch_get_main_queue(), ^{
        [center getPendingNotificationRequestsWithCompletionHandler:^(NSArray<UNNotificationRequest *> * _Nonnull requests) {
                self.cachedPendingNotificationRequests = requests;
        }];
    });
}
```

**Comment by yanmasharski** [comment] 2021-10-11 12:26
Little bit improved solution
`
- (void)updateScheduledNotificationList
{
    UNUserNotificationCenter* center = [UNUserNotificationCenter currentNotificationCenter];
    if (@available(iOS 15, *)) {
        dispatch_async(dispatch_get_main_queue(), ^{
            [center getPendingNotificationRequestsWithCompletionHandler:^(NSArray<UNNotificationRequest *> * _Nonnull requests) {
                    self.cachedPendingNotificationRequests = requests;
            }];
        });
    } else {
        [center getPendingNotificationRequestsWithCompletionHandler:^(NSArray<UNNotificationRequest *> * _Nonnull requests) {
                self.cachedPendingNotificationRequests = requests;
        }];
    }
        
}
`

**Comment by aurimasc** [comment] 2021-10-15 08:14
Under what conditions does this occur?
I cannot reproduce this issue using latest notifications package.

**Comment by neHCuoHEpa** [comment] 2021-11-01 22:01
Full code solution. Add that script to any Editor folder, should be fix the problem

`public class ApplePostProcess : MonoBehaviour
{
#if UNITY_IOS
    [PostProcessBuild(1)]
    public static void OnPostProcessBuild(BuildTarget buildTarget, string pathToXcode)
    {
        if (buildTarget == BuildTarget.iOS)
        {
            FixediOS13NotificationBug(pathToXcode);
        }
    }
    private static void FixediOS13NotificationBug(string pathToXcode)
    {
        string managerPath = pathToXcode + "/Libraries/com.unity.mobile.notifications/Runtime/iOS/Plugins/UnityNotificationManager.m";
        var text = File.ReadAllLines(managerPath).ToList();

        for (int i = 0; i < text.Count; i++)
        {
            if (text[i] == @"- (void)updateScheduledNotificationList")
            {
                text.RemoveRange(i, 7);
                text.Insert(i, @"- (void)updateScheduledNotificationList
{
    UNUserNotificationCenter* center = [UNUserNotificationCenter currentNotificationCenter];
    if (@available(iOS 15, *))
    {
        dispatch_async(dispatch_get_main_queue(), ^{
            [center getPendingNotificationRequestsWithCompletionHandler:^(NSArray < UNNotificationRequest *> *_Nonnull requests) {
                self.cachedPendingNotificationRequests = requests;
            }];
        });
    }
    else
    {
        [center getPendingNotificationRequestsWithCompletionHandler:^(NSArray < UNNotificationRequest *> *_Nonnull requests) {
            self.cachedPendingNotificationRequests = requests;
        }];
    }

}");
                break;
            }
        }
        
        File.WriteAllLines(managerPath, text.ToArray());
    }
#endif
}`

**Comment by celp** [comment] 2021-11-04 12:59
Hi All,
I just received a message from Unity that the issue has been added to the Issue Tracker.
I'm waiting for the fix.

https://issuetracker.unity3d.com/issues/ios-app-freezes-slash-crashes-when-both-mobile-notifications-and-firebase-are-used

**Comment by aurimasc** [comment] 2021-11-30 16:28
Should be fixed by this: https://github.com/Unity-Technologies/com.unity.mobile.notifications/pull/130

**Closed by aurimasc** 2021-11-30 16:28 UTC

**Comment by ismail-koroglu** [comment] 2021-12-08 09:23
@neHCuoHEpa thank you. This works.
