### ISSUE TITLE
Mobile Notifications Version 2.0.1: Android - Fatal Exception: java.lang.Error

### ISSUE THREAD

**Issue by andoprof** [Unity-Technologies/com.unity.mobile.notifications#183] opened 2022-05-02 04:35 UTC
**Fatal Exception: java.lang.Error**
Unity version: 2020.3.33f1
Build Type: Release
Scripting Backend: IL2CPP
ABI: armeabi-v7a
Strip Engine Code: true

**Samsung 61%** 
11% Galaxy J2
9% Galaxy J1 Mini
8% Galaxy J1 Ace
33% Other (11)

**Operating systems:**
95% Android 5
3% Android 6
2% Android 7

**Device states**
0% In background
0% Rooted
77% Proximity on

Caused by java.lang.NoSuchMethodError: No virtual method getActiveNotifications()[Landroid/service/notification/StatusBarNotification; in class Landroid/app/NotificationManager; or its super classes (declaration of 'android.app.NotificationManager' appears in /system/framework/framework.jar:classes2.dex)
       at com.unity.androidnotifications.UnityNotificationManager.findInvalidNotificationIds(UnityNotificationManager.java:430)
       at com.unity.androidnotifications.UnityNotificationManager.performNotificationHousekeeping(UnityNotificationManager.java:403)
       at com.unity.androidnotifications.UnityNotificationManager.lambda$triggerHousekeeping$0(UnityNotificationManager.java:387)
       at com.unity.androidnotifications.-$$Lambda$UnityNotificationManager$fSttc7CuZmP-kDH-q_FquZSJ7Yk.run(lambda)
       at java.lang.Thread.run(Thread.java:818)
       
_Please check and fix it! Thanks!_

**Comment by aurimasc** [comment] 2022-05-02 15:17
This is duplicate of case 1423875.

**Closed by aurimasc** 2022-05-02 15:17 UTC
