### ISSUE TITLE
Missing "exported" attributed in manifest while generating APK

### ISSUE THREAD

**Issue by AntonioTangeloGames** [Unity-Technologies/com.unity.mobile.notifications#143] opened 2022-01-13 12:06 UTC
After the Behavior changes in Android, If your app targets Android 12 or higher and contains activities, services, or broadcast receivers that use intent filters, you must explicitly declare the "android: exported" attribute for these app components.

This is not happening right now, failing when the apk is uploaded to android. This attribute should be added into the manifest when it is generated in the class "AndroidNotificationPostProcessor" line 118 approx.

https://developer.android.com/about/versions/12/behavior-changes-12#exported

Is happening in Android, Unity 2020.3.20f, "Mobile notification package" version 1.4.2 ( the last when this was written )

**Comment by AntonioTangeloGames** [comment] 2022-01-13 14:27
We have a custom manifest as well, but we don't have on it the receiver for mobile notification. 
We could add it and fix the issue, but I think that this is something that the package should provide to us.

**Comment by dcosmin-97** [comment] 2022-01-18 18:12
The issue is solved in 1.5.0, but the tag is not modified yet to 1.5.0 so you cannot update yet, maybe they forgot to add it

**Comment by aurimasc** [comment] 2022-01-19 15:19
This issue is fixed in master.

**Closed by aurimasc** 2022-01-19 15:19 UTC
